### ISSUE TITLE
Epoch 0.3.3.0

### ISSUE THREAD

**Issue by missjennabee** [BoleParty/HighLoot#1]
Firstly, thanks for this, really simplified my life lol.  Just a quick question though - Does anything need to be done to this to make it compatible with the latest version of Epoch (0.3.3.0)? Doesn't seem to be working for me anymore. 

Thanks in advance!

**Comment by BoleParty** [comment]
check ur emails :)

**Comment by missjennabee** [comment]
Got it sorted :) thanks again!
